"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, DatabaseZap, Loader2, Pencil, Plus, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Store, Trash2, Truck } from "lucide-react";

import { apiFetch } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

type CustomFieldType = "text" | "number" | "boolean" | "select" | "date" | "json";

type ProductField = {
  id: string;
  organizationId: string;
  key: string;
  label: string;
  type: CustomFieldType;
  required: boolean;
  options: string[];
  defaultValue?: unknown;
  order: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

type FieldFormState = {
  label: string;
  type: CustomFieldType;
  required: boolean;
  optionsText: string;
  defaultValue: string;
  order: number;
  isActive: boolean;
};

type DefaultProductField = {
  key: string;
  label: string;
  type: string;
  required: boolean;
  description: string;
};

type AttributeTemplateField = {
  label: string;
  type: CustomFieldType;
  required?: boolean;
  options?: string[];
  defaultValue?: unknown;
};

type AttributeTemplate = {
  id: string;
  icon: any;
  title: string;
  description: string;
  fields: AttributeTemplateField[];
};

const defaultProductFields: DefaultProductField[] = [
  { key: "name", label: "Product name", type: "text", required: true, description: "Main product name used across the app, APIs, imports, and integrations." },
  { key: "sku", label: "SKU", type: "text", required: true, description: "Unique product identifier generated by NexStock and used for updates." },
  { key: "description", label: "Description", type: "text", required: false, description: "Product details, notes, and customer-facing description." },
  { key: "category", label: "Category", type: "text", required: false, description: "Product grouping used for filters, reports, and mapping." },
  { key: "price", label: "Price", type: "number", required: true, description: "Selling price for the product." },
  { key: "cost", label: "Cost", type: "number", required: false, description: "Internal cost for margin and operational review." },
  { key: "quantity", label: "Quantity", type: "number", required: true, description: "Current available stock." },
  { key: "lowStockLevel", label: "Low-stock level", type: "number", required: true, description: "Threshold used by alerts and dashboard readiness." },
  { key: "images", label: "Images", type: "list", required: false, description: "Product image URLs from upload, import, or integration sync." },
];

const attributeTemplates: AttributeTemplate[] = [
  {
    id: "retail",
    icon: Store,
    title: "Retail essentials",
    description: "Common attributes for stores, apparel, general merchandise, and catalog cleanup.",
    fields: [
      { label: "Brand", type: "text" },
      { label: "Barcode", type: "text" },
      { label: "Color", type: "text" },
      { label: "Size", type: "select", options: ["XS", "S", "M", "L", "XL", "XXL"] },
      { label: "Material", type: "text" },
      { label: "Warranty months", type: "number" },
    ],
  },
  {
    id: "ecommerce",
    icon: Sparkles,
    title: "Ecommerce catalog",
    description: "Attributes for online stores, SEO, external categories, and storefront mapping.",
    fields: [
      { label: "SEO title", type: "text" },
      { label: "SEO description", type: "text" },
      { label: "Product tags", type: "text" },
      { label: "Shopify handle", type: "text" },
      { label: "External category", type: "text" },
      { label: "Online status", type: "select", options: ["published", "draft", "hidden"] },
    ],
  },
  {
    id: "supplier",
    icon: Truck,
    title: "Supplier & distribution",
    description: "Attributes for suppliers, distributors, pack sizes, lead times, and external item IDs.",
    fields: [
      { label: "Supplier name", type: "text" },
      { label: "Supplier SKU", type: "text" },
      { label: "Pack size", type: "number" },
      { label: "Minimum order quantity", type: "number" },
      { label: "Lead time days", type: "number" },
      { label: "Zoho item ID", type: "text" },
    ],
  },
];

const emptyForm: FieldFormState = {
  label: "",
  type: "text",
  required: false,
  optionsText: "",
  defaultValue: "",
  order: 0,
  isActive: true,
};

export function ProductFieldsManager() {
  const [fields, setFields] = useState<ProductField[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [isApplyingTemplate, setIsApplyingTemplate] = useState<string | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingField, setEditingField] = useState<ProductField | null>(null);
  const [form, setForm] = useState<FieldFormState>(emptyForm);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const activeFields = useMemo(() => fields.filter((field) => field.isActive), [fields]);
  const inactiveFields = useMemo(() => fields.filter((field) => !field.isActive), [fields]);
  const requiredCount = defaultProductFields.filter((field) => field.required).length + activeFields.filter((field) => field.required).length;
  const existingKeys = useMemo(() => new Set([...defaultProductFields.map((field) => field.key.toLowerCase()), ...fields.map((field) => field.key.toLowerCase())]), [fields]);

  useEffect(() => {
    void loadFields();
  }, []);

  async function loadFields() {
    setIsLoading(true);
    setError(null);
    try {
      const data = await apiFetch<ProductField[]>("/api/product-fields");
      setFields(data);
    } catch (err: any) {
      setError(err.message ?? "Failed to load product attributes");
    } finally {
      setIsLoading(false);
    }
  }

  function generateKeyFromLabel(value: string) {
    return value.trim().replace(/\s+/g, "_").replace(/[^a-zA-Z0-9_]/g, "");
  }

  function templateStatus(template: AttributeTemplate) {
    const missing = template.fields.filter((field) => !existingKeys.has(generateKeyFromLabel(field.label).toLowerCase()));
    return { missing, complete: missing.length === 0 };
  }

  function openCreateDialog() {
    setEditingField(null);
    setForm({ ...emptyForm, order: fields.length + 1 });
    setError(null);
    setNotice(null);
    setIsDialogOpen(true);
  }

  function openEditDialog(field: ProductField) {
    setEditingField(field);
    setForm({
      label: field.label,
      type: field.type,
      required: field.required,
      optionsText: field.options?.join("\n") ?? "",
      defaultValue: field.defaultValue === undefined || field.defaultValue === null ? "" : typeof field.defaultValue === "object" ? JSON.stringify(field.defaultValue, null, 2) : String(field.defaultValue),
      order: field.order,
      isActive: field.isActive,
    });
    setError(null);
    setNotice(null);
    setIsDialogOpen(true);
  }

  async function createFieldFromTemplate(templateField: AttributeTemplateField, order: number) {
    const label = templateField.label.trim();
    const key = generateKeyFromLabel(label);
    if (!label || !key || existingKeys.has(key.toLowerCase())) return false;
    await apiFetch("/api/product-fields", {
      method: "POST",
      body: JSON.stringify({
        label,
        type: templateField.type,
        required: Boolean(templateField.required),
        options: templateField.options ?? [],
        defaultValue: templateField.defaultValue,
        order,
        isActive: true,
      }),
    });
    existingKeys.add(key.toLowerCase());
    return true;
  }

  async function applyTemplate(template: AttributeTemplate) {
    const status = templateStatus(template);
    if (status.complete) {
      setNotice(`${template.title} is already applied.`);
      return;
    }

    setIsApplyingTemplate(template.id);
    setError(null);
    setNotice(null);
    try {
      let created = 0;
      let order = fields.length + 1;
      for (const templateField of status.missing) {
        const didCreate = await createFieldFromTemplate(templateField, order);
        if (didCreate) {
          created += 1;
          order += 1;
        }
      }
      await loadFields();
      setNotice(`${template.title} applied. ${created} attribute${created === 1 ? "" : "s"} added.`);
    } catch (err: any) {
      setError(err.message ?? `Failed to apply ${template.title}`);
    } finally {
      setIsApplyingTemplate(null);
    }
  }

  async function handleSubmit() {
    setError(null);
    setNotice(null);
    const label = form.label.trim();
    const key = generateKeyFromLabel(label);

    if (!label) return setError("Attribute label is required");
    if (!key) return setError("Attribute label must contain at least one valid character");
    if (defaultProductFields.some((field) => field.key.toLowerCase() === key.toLowerCase())) return setError("This attribute already exists as a default product attribute. Use a different label.");

    const options = form.optionsText.split("\n").map((option) => option.trim()).filter(Boolean);
    if (form.type === "select" && options.length === 0) return setError("Select attributes require at least one option");

    let defaultValue: unknown = undefined;
    try {
      defaultValue = parseDefaultValue(form.type, form.defaultValue);
    } catch (err: any) {
      return setError(err.message ?? "Invalid default value");
    }

    const payload = { label, type: form.type, required: form.required, options, defaultValue, order: Number(form.order) || 0, isActive: form.isActive };
    setIsSaving(true);
    try {
      if (editingField) await apiFetch(`/api/product-fields/${editingField.id}`, { method: "PATCH", body: JSON.stringify(payload) });
      else await apiFetch("/api/product-fields", { method: "POST", body: JSON.stringify(payload) });
      setIsDialogOpen(false);
      await loadFields();
      setNotice(editingField ? "Attribute updated." : "Attribute created.");
    } catch (err: any) {
      setError(err.message ?? "Failed to save product attribute");
    } finally {
      setIsSaving(false);
    }
  }

  async function deactivateField(field: ProductField) {
    if (!window.confirm(`Deactivate "${field.label}"? Existing product values will be preserved.`)) return;
    setError(null);
    setNotice(null);
    try {
      await apiFetch(`/api/product-fields/${field.id}`, { method: "DELETE" });
      await loadFields();
      setNotice(`"${field.label}" deactivated.`);
    } catch (err: any) {
      setError(err.message ?? "Failed to deactivate product attribute");
    }
  }

  async function reactivateField(field: ProductField) {
    setError(null);
    setNotice(null);
    try {
      await apiFetch(`/api/product-fields/${field.id}`, { method: "PATCH", body: JSON.stringify({ isActive: true }) });
      await loadFields();
      setNotice(`"${field.label}" reactivated.`);
    } catch (err: any) {
      setError(err.message ?? "Failed to reactivate product attribute");
    }
  }

  return (
    <>
      <section className="border bg-card/95">
        <div className="grid divide-y sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-4">
          <SummaryMetric title="All attributes" value={defaultProductFields.length + fields.length} description="Default plus additional attributes" />
          <SummaryMetric title="Default attributes" value={defaultProductFields.length} description="Built into every product" />
          <SummaryMetric title="Additional attributes" value={activeFields.length} description="Active business attributes" />
          <SummaryMetric title="Required attributes" value={requiredCount} description="Required on product forms" />
        </div>
      </section>

      <section className="border bg-card/95">
        <SectionHeader
          icon={Sparkles}
          title="Attribute templates"
          description="Start with common product-data templates instead of creating every attribute manually. Templates skip attributes you already have."
        />
        <div className="grid gap-4 border-t p-5 lg:grid-cols-3">
          {attributeTemplates.map((template) => {
            const status = templateStatus(template);
            const Icon = template.icon;
            return (
              <section key={template.id} className="flex min-h-[260px] flex-col rounded-2xl border bg-background p-4">
                <div className="flex items-start justify-between gap-3">
                  <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span>
                  <Badge variant={status.complete ? "default" : "secondary"}>{status.complete ? "Applied" : `${status.missing.length} missing`}</Badge>
                </div>
                <h3 className="mt-4 font-semibold tracking-tight">{template.title}</h3>
                <p className="mt-2 text-sm leading-6 text-muted-foreground">{template.description}</p>
                <div className="mt-4 flex flex-wrap gap-2">
                  {template.fields.slice(0, 4).map((field) => <Badge key={field.label} variant="outline">{field.label}</Badge>)}
                  {template.fields.length > 4 && <Badge variant="outline">+{template.fields.length - 4}</Badge>}
                </div>
                <Button type="button" onClick={() => applyTemplate(template)} disabled={Boolean(isApplyingTemplate) || status.complete} className="mt-auto rounded-xl">
                  {isApplyingTemplate === template.id ? <><Loader2 className="h-4 w-4 animate-spin" />Applying...</> : status.complete ? "Already applied" : "Apply template"}
                </Button>
              </section>
            );
          })}
        </div>
      </section>

      <section className="border bg-card/95">
        <SectionHeader
          icon={Settings2}
          title="Unified product attributes"
          description="Default attributes and additional business attributes are shown together so products, imports, mappings, and APIs use one model."
          action={<Button onClick={openCreateDialog} className="rounded-xl"><Plus className="h-4 w-4" />Add attribute</Button>}
        />

        {error && <div className="border-t border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
        {notice && <div className="border-t border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</div>}

        <section className="border-t">
          <SectionHeader icon={ShieldCheck} title="Default product attributes" description="These attributes are locked because they power core product, inventory, import, and sync behavior." />
          <div className="grid divide-y border-t md:grid-cols-2 md:divide-x md:divide-y-0">
            <div className="divide-y">
              {defaultProductFields.filter((_, index) => index % 2 === 0).map((field) => <DefaultFieldRow key={field.key} field={field} />)}
            </div>
            <div className="divide-y">
              {defaultProductFields.filter((_, index) => index % 2 === 1).map((field) => <DefaultFieldRow key={field.key} field={field} />)}
            </div>
          </div>
        </section>

        {isLoading ? (
          <div className="border-t p-8 text-center text-sm text-muted-foreground">
            <Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Loading additional product attributes...
          </div>
        ) : fields.length === 0 ? (
          <EmptyState onCreate={openCreateDialog} />
        ) : (
          <div className="border-t">
            <FieldSection title="Additional active attributes" description="These attributes extend the default product model and appear on forms, imports, mapping, and APIs." fields={activeFields} emptyMessage="No additional active attributes yet." onEdit={openEditDialog} onDeactivate={deactivateField} onReactivate={reactivateField} />
            {inactiveFields.length > 0 && <FieldSection title="Inactive additional attributes" description="Hidden from new product forms, but existing values remain preserved." fields={inactiveFields} emptyMessage="No inactive attributes." onEdit={openEditDialog} onDeactivate={deactivateField} onReactivate={reactivateField} />}
          </div>
        )}
      </section>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">
          <DialogHeader><DialogTitle>{editingField ? "Edit product attribute" : "Create product attribute"}</DialogTitle><DialogDescription>Add a business-specific attribute that joins the default product attributes across product forms, imports, and integration mappings.</DialogDescription></DialogHeader>
          <div className="space-y-5">
            {error && <div className="border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
            <div className="grid gap-4 md:grid-cols-2"><Field label="Label" required><Input className="rounded-xl" value={form.label} placeholder="Supplier code" onChange={(event) => setForm((prev) => ({ ...prev, label: event.target.value }))} /></Field><Field label="Generated key"><Input value={generateKeyFromLabel(form.label)} readOnly placeholder="Supplier_code" className="rounded-xl bg-muted text-muted-foreground" /></Field></div>
            <div className="grid gap-4 md:grid-cols-2"><Field label="Type" required><Select value={form.type} onValueChange={(value: CustomFieldType) => setForm((prev) => ({ ...prev, type: value, optionsText: value === "select" ? prev.optionsText : "" }))}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Select attribute type" /></SelectTrigger><SelectContent><SelectItem value="text">Text</SelectItem><SelectItem value="number">Number</SelectItem><SelectItem value="boolean">Boolean</SelectItem><SelectItem value="select">Select</SelectItem><SelectItem value="date">Date</SelectItem><SelectItem value="json">JSON</SelectItem></SelectContent></Select></Field><Field label="Display order"><Input className="rounded-xl" type="number" min={0} value={form.order} onChange={(event) => setForm((prev) => ({ ...prev, order: Number(event.target.value) }))} /></Field></div>
            {form.type === "select" && <Field label="Options" required><Textarea value={form.optionsText} placeholder={"Small\nMedium\nLarge"} className="min-h-28 resize-none rounded-xl" onChange={(event) => setForm((prev) => ({ ...prev, optionsText: event.target.value }))} /><p className="text-xs text-muted-foreground">Add one option per line.</p></Field>}
            <Field label="Default value"><DefaultValueInput form={form} setForm={setForm} /></Field>
            <div className="grid gap-4 border bg-muted/20 p-4 md:grid-cols-2"><ToggleRow label="Required" description="Product creation must provide this value." checked={form.required} onChange={(checked) => setForm((prev) => ({ ...prev, required: checked }))} /><ToggleRow label="Active" description="Show this attribute on product forms." checked={form.isActive} onChange={(checked) => setForm((prev) => ({ ...prev, isActive: checked }))} /></div>
          </div>
          <DialogFooter className="gap-2 sm:gap-0"><Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)} disabled={isSaving} className="rounded-xl">Cancel</Button><Button type="button" onClick={handleSubmit} disabled={isSaving} className="rounded-xl">{isSaving ? <><Loader2 className="h-4 w-4 animate-spin" />Saving...</> : editingField ? "Save changes" : "Create attribute"}</Button></DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

function SectionHeader({ icon: Icon, title, description, action }: { icon: any; title: string; description?: string; action?: React.ReactNode }) {
  return <div className="flex flex-row items-start justify-between gap-4 p-5"><div><h2 className="flex items-center gap-2 text-lg font-semibold tracking-tight"><Icon className="h-5 w-5" />{title}</h2>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{action}</div>;
}

function SummaryMetric({ title, value, description }: { title: string; value: number; description: string }) {
  return <div className="flex items-center justify-between p-4"><div><p className="text-sm text-muted-foreground">{title}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></div><span className="flex h-10 w-10 items-center justify-center bg-primary/10 text-primary"><SlidersHorizontal className="h-4 w-4" /></span></div>;
}

function DefaultFieldRow({ field }: { field: DefaultProductField }) {
  return <div className="p-4"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{field.label}</p><Badge variant="secondary">Default</Badge>{field.required && <Badge>Required</Badge>}<Badge variant="outline">{field.type}</Badge><Badge variant="outline"><ShieldCheck className="h-3 w-3" />Locked</Badge></div><p className="mt-2 text-sm text-muted-foreground">{field.description}</p><p className="mt-2 font-mono text-xs text-muted-foreground">{field.key}</p></div>;
}

function EmptyState({ onCreate }: { onCreate: () => void }) {
  return <div className="border-t bg-muted/20 p-10 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center bg-primary/10 text-primary"><Settings2 className="h-7 w-7" /></div><h3 className="mt-4 text-lg font-semibold">No additional attributes yet</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Default attributes already cover the basics. Apply a template or add custom attributes like brand, supplier code, color, material, warranty months, or external category.</p><Button className="mt-5 rounded-xl" onClick={onCreate}><Plus className="h-4 w-4" />Create attribute</Button></div>;
}

function FieldSection({ title, description, fields, emptyMessage, onEdit, onDeactivate, onReactivate }: { title: string; description: string; fields: ProductField[]; emptyMessage: string; onEdit: (field: ProductField) => void; onDeactivate: (field: ProductField) => void; onReactivate: (field: ProductField) => void }) {
  return <section className="border-t"><div className="p-5"><h3 className="font-semibold tracking-tight">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{fields.length === 0 ? <div className="border-t p-5 text-sm text-muted-foreground">{emptyMessage}</div> : <div className="divide-y border-t">{fields.map((field) => <FieldRow key={field.id} field={field} onEdit={onEdit} onDeactivate={onDeactivate} onReactivate={onReactivate} />)}</div>}</section>;
}

function FieldRow({ field, onEdit, onDeactivate, onReactivate }: { field: ProductField; onEdit: (field: ProductField) => void; onDeactivate: (field: ProductField) => void; onReactivate: (field: ProductField) => void }) {
  return <div className="flex flex-col gap-4 p-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0 space-y-2"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{field.label}</p><Badge variant={field.isActive ? "default" : "secondary"}>{field.isActive ? "Active" : "Inactive"}</Badge>{field.required && <Badge variant="destructive">Required</Badge>}<Badge variant="outline">{field.type}</Badge><Badge variant="secondary">Additional</Badge></div><div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span>Key: {field.key}</span><span>Order: {field.order}</span>{field.options?.length > 0 && <span>Options: {field.options.join(", ")}</span>}</div></div><div className="flex flex-wrap gap-2">{!field.isActive && <Button type="button" variant="outline" size="sm" onClick={() => onReactivate(field)} className="rounded-xl"><CheckCircle2 className="h-4 w-4" />Reactivate</Button>}<Button type="button" variant="outline" size="sm" onClick={() => onEdit(field)} className="rounded-xl"><Pencil className="h-4 w-4" />Edit</Button>{field.isActive && <Button type="button" variant="destructive" size="sm" onClick={() => onDeactivate(field)} className="rounded-xl"><Trash2 className="h-4 w-4" />Deactivate</Button>}</div></div>;
}

function DefaultValueInput({ form, setForm }: { form: FieldFormState; setForm: React.Dispatch<React.SetStateAction<FieldFormState>> }) {
  if (form.type === "boolean") return <Select value={form.defaultValue || ""} onValueChange={(value) => setForm((prev) => ({ ...prev, defaultValue: value }))}><SelectTrigger className="rounded-xl"><SelectValue placeholder="No default value" /></SelectTrigger><SelectContent><SelectItem value="true">True</SelectItem><SelectItem value="false">False</SelectItem></SelectContent></Select>;
  if (form.type === "json") return <Textarea value={form.defaultValue} placeholder='{ "example": true }' className="min-h-28 resize-none rounded-xl font-mono text-sm" onChange={(event) => setForm((prev) => ({ ...prev, defaultValue: event.target.value }))} />;
  return <Input className="rounded-xl" type={form.type === "number" ? "number" : form.type === "date" ? "date" : "text"} value={form.defaultValue} placeholder={getDefaultPlaceholder(form.type)} onChange={(event) => setForm((prev) => ({ ...prev, defaultValue: event.target.value }))} />;
}

function ToggleRow({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <div className="flex items-center justify-between gap-4"><div><Label>{label}</Label><p className="text-xs text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={onChange} /></div>;
}

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) {
  return <div className="space-y-2"><Label>{label}{required && <span className="ml-1 text-destructive">*</span>}</Label>{children}</div>;
}

function parseDefaultValue(type: CustomFieldType, rawValue: string) {
  const value = rawValue.trim();
  if (!value) return undefined;
  if (type === "number") {
    const numberValue = Number(value);
    if (Number.isNaN(numberValue)) throw new Error("Default value must be a valid number");
    return numberValue;
  }
  if (type === "boolean") {
    if (value !== "true" && value !== "false") throw new Error("Default value must be true or false");
    return value === "true";
  }
  if (type === "json") {
    try { return JSON.parse(value); } catch { throw new Error("Default value must be valid JSON"); }
  }
  if (type === "date") {
    const date = Date.parse(value);
    if (Number.isNaN(date)) throw new Error("Default value must be a valid date");
    return value;
  }
  return value;
}

function getDefaultPlaceholder(type: CustomFieldType) {
  switch (type) {
    case "text": return "Example value";
    case "number": return "10";
    case "date": return "";
    case "select": return "Must match one option";
    default: return "";
  }
}
